/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ingredient_gui;

import java.awt.Dimension;
import java.awt.Graphics2D;
import java.awt.Image;
import java.awt.geom.AffineTransform;
import java.awt.image.BufferedImage;
import java.io.File;
import java.io.IOException;
import java.lang.reflect.Array;
import java.net.URL;
import java.util.List;

import javax.imageio.ImageIO;
import javax.swing.Icon;
import javax.swing.ImageIcon;
import javax.swing.JLabel;

import com.google.gson.Gson;
import com.google.gson.JsonArray;
import com.google.gson.JsonObject;
import com.google.gson.JsonParser;
import com.ibm.watson.developer_cloud.visual_recognition.v3.VisualRecognition;
import com.ibm.watson.developer_cloud.visual_recognition.v3.model.ClassifyImagesOptions;
import com.ibm.watson.developer_cloud.visual_recognition.v3.model.ImageClassification;
import com.ibm.watson.developer_cloud.visual_recognition.v3.model.VisualClassification;

/**
 *
 * @author Evan
 */
public class gui extends javax.swing.JFrame {
	private String[] imgNames = new ImgRenderer().getImageNames();
	private VisualRecognition service = new VisualRecognition("2016-05-20");
	
    /**
     * Creates new form gui
     */
    public gui() {
        initComponents();
        setImageList();
    }
    
    public void setImageList() {
       ImgRenderer renderer = new ImgRenderer();
        imageList.setCellRenderer(renderer);
        renderer.setPreferredSize(new Dimension(628, 101));

        for (int i = 0; i < imgNames.length; ++i) {
            System.out.println(imgNames[i]);
            JLabel ic = new JLabel();
            ic.setIcon(new ImageIcon("img" + imgNames[i]));
            imageList.add(ic);
        }

        
    }
    /** Returns an ImageIcon, or null if the path was invalid. */
    protected static ImageIcon createImageIcon(String path) {
        java.net.URL imgURL = ImgRenderer.class.getResource(path);
        if (imgURL != null) {
            return new ImageIcon(imgURL);
        } else {
            System.err.println("Couldn't find file: " + path);
                return null;
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
    	
		service.setApiKey("af16cab33a7b47433d5ce63aace1d08f379afa2a");
    	
        selectedImage = new javax.swing.JPanel();
        img = new javax.swing.JLabel();
        imageSelect = new javax.swing.JScrollPane();
        imageList = new javax.swing.JList();
        setImage = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        watsonInfo = new javax.swing.JTextArea();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        
        int imageHeight = 800;
        int imageWidth = 525; 
        System.out.println("imageHeight: " + imageHeight);
        ImageIcon icon = null;
        BufferedImage stock = null;
        BufferedImage after = null;
    
		try {
			stock = ImageIO.read(new File("img/01-cat-wants-to-tell-you-laptop.jpg"));
			
			//icon = new ImageIcon(stock);
			System.out.println("Stock Width: "+ stock.getWidth()+"\nStock Height: "+stock.getHeight()+"\nScale W: "+ (double)imageWidth/stock.getWidth()+"\nScale H: " +(double)imageHeight/stock.getWidth());
			/*
			icon = new ImageIcon(scale
					(
							stock, stock.getType(),stock.getWidth(),stock.getHeight(),
							(imageWidth/stock.getWidth()),(imageHeight/stock.getHeight())
					)
			);
			*/
			after = new BufferedImage(imageWidth,imageHeight,stock.getType());
			icon = new ImageIcon(stock.getScaledInstance(imageHeight, imageWidth, NORMAL));
			//stock = (BufferedImage) getClass().getResource("/img/donut platter.jpg").getContent();
		} catch (IOException e) {
			// TODO Auto-generated catch block
			e.printStackTrace();
		}
		if(stock != null) {
			
			//img.setIcon(new javax.swing.ImageIcon(scale(stock, stock.getType(),stock.getWidth(),stock.getHeight(),(img.getWidth()/stock.getWidth()),(img.getHeight()/stock.getHeight())))); // NOI18N
			img.setIcon(icon);
			//img.setText("jLabel1");
		}else {
			System.out.println("was null");
		}
        

        javax.swing.GroupLayout selectedImageLayout = new javax.swing.GroupLayout(selectedImage);
        selectedImage.setLayout(selectedImageLayout);
        selectedImageLayout.setHorizontalGroup(
            selectedImageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(img, javax.swing.GroupLayout.DEFAULT_SIZE, 800, javax.swing.GroupLayout.DEFAULT_SIZE)
        );
        selectedImageLayout.setVerticalGroup(
            selectedImageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(img, javax.swing.GroupLayout.DEFAULT_SIZE, 525, javax.swing.GroupLayout.DEFAULT_SIZE)
        );

        imageList.setLayoutOrientation(javax.swing.JList.HORIZONTAL_WRAP);
        imageSelect.setViewportView(imageList);

        setImage.setText("Choose");
        setImage.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                setImageActionPerformed(evt);
            }
        });

        watsonInfo.setColumns(20);
        watsonInfo.setRows(5);
        watsonInfo.setMaximumSize(new java.awt.Dimension(172, 388));
        jScrollPane1.setViewportView(watsonInfo);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(imageSelect, javax.swing.GroupLayout.PREFERRED_SIZE, 628, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(setImage))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(selectedImage, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane1)))
                .addContainerGap(14, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(selectedImage, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jScrollPane1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(setImage, javax.swing.GroupLayout.DEFAULT_SIZE, 101, Short.MAX_VALUE)
                    .addComponent(imageSelect))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void setImageActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_setImageActionPerformed
        //String returnedInfo = "PUT WATSON INFO HERE";
        int i = imageList.getSelectedIndex();
        
		ClassifyImagesOptions options = new ClassifyImagesOptions.Builder()
				  .images(new File("img/01-cat-wants-to-tell-you-laptop.jpg"))
				  .build();
				//return a result for us to print using VisualRecognition service and 
				VisualClassification result = service.classify(options).execute();
				List<ImageClassification> ic = result.getImages();
        //img.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/01-cat-wants-to-tell-you-laptop.jpg"))); // update "img" field
		Gson gson = new Gson();
		String jsonInString = gson.toJson(result);
		System.out.println(jsonInString);
        watsonInfo.setText(result.toString());
    }//GEN-LAST:event_setImageActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(gui.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(gui.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(gui.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(gui.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new gui().setVisible(true);
            }
        });
    }
    
    public static BufferedImage scale(BufferedImage sbi, int imageType, int dWidth, int dHeight, double fWidth, double fHeight) {
        BufferedImage dbi = null;
        if(sbi != null) {
            dbi = new BufferedImage(dWidth, dHeight, imageType);
            Graphics2D g = dbi.createGraphics();
            AffineTransform at = AffineTransform.getScaleInstance(fWidth, fHeight);
            g.drawRenderedImage(sbi, at);
        }
        return dbi;
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JList imageList;
    private javax.swing.JScrollPane imageSelect;
    private javax.swing.JLabel img;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JPanel selectedImage;
    private javax.swing.JButton setImage;
    private javax.swing.JTextArea watsonInfo;
    // End of variables declaration//GEN-END:variables
}
